version: '3'

services:
  wordoo.containerized:
    image: wordoo.containerized:dev
    build:
      args:
        source: obj/Docker/empty/
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
    volumes:
      - C:\Users\dgartne\Source\Repos\Wordoo.Containerized\Wordoo.Containerized:/app
      - C:\Users\dgartne\vsdbg:/remote_debugger:ro
      - C:\Users\dgartne\.nuget\packages\:/root/.nuget/packages:ro
      - C:\Users\dgartne\.nuget\packages\:/root/.nuget/fallbackpackages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/fallbackpackages  bin/Release/netcoreapp1.1/Wordoo.Containerized.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
